version: '3'
services:
  gamedock:
    image: ikqr/gamedock:latest
    ports:
      - 8000:80
    environment:
      - "ConnectionStrings__SQLite=Data Source=/uploads/GameDock.db;"
      - "ConnectionStrings__FileStorage=/uploads"
    volumes:
      - /uploads-docker:/uploads
      - /var/run/docker.sock:/var/run/docker.sock